[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Contacts"
  pageRef = "contacts"
  weight = 30

[[main]]
  name = "My DevOps Blog"
  url = "https://verydevops.com"
  weight = 40
  [main.params]
    external = true
